[workspace]
resolver = "3"
members = [
    "crates/array",
    "crates/double_pointer",
    "crates/hash",
    "crates/linked_list",
    "crates/matrix",
    "crates/sliding_window",
    "crates/sub_sequence",
    "crates/tree",
]
